"""Tests for the optional cogsecskills.yaml configuration."""

from __future__ import annotations

from pathlib import Path

import pytest

from cogsecskills.config import CONFIG_FILENAME, Config, config_path, load_config
from cogsecskills.harness import HARNESSES


def _write(root: Path, text: str) -> None:
    (root / CONFIG_FILENAME).write_text(text, encoding="utf-8")


def test_defaults_when_absent(tmp_path):
    cfg = load_config(tmp_path)
    assert cfg.harnesses == HARNESSES
    assert cfg.min_workflow_steps == 3
    assert cfg.min_anti_criteria == 2
    assert cfg.require_references is False
    assert config_path(tmp_path) == tmp_path / CONFIG_FILENAME


def test_defaults_classmethod():
    assert Config.defaults().harnesses == HARNESSES


def test_load_overrides(tmp_path):
    _write(
        tmp_path,
        "harnesses: [claude, codex, hermes, gemini]\n"
        "quality:\n  min_workflow_steps: 4\n  min_anti_criteria: 1\n"
        "  require_references: true\n",
    )
    cfg = load_config(tmp_path)
    assert cfg.harnesses == ("claude", "codex", "hermes", "gemini")
    assert cfg.min_workflow_steps == 4
    assert cfg.min_anti_criteria == 1
    assert cfg.require_references is True


def test_empty_file_is_defaults(tmp_path):
    _write(tmp_path, "")
    assert load_config(tmp_path).harnesses == HARNESSES


@pytest.mark.parametrize(
    "text, match",
    [
        ("- a\n- b\n", "top-level mapping"),
        ("harnesses: []\n", "non-empty list"),
        ("harnesses: notalist\n", "non-empty list"),
        ("harnesses: [' ', '']\n", "resolved to empty"),
        ("quality: notamap\n", "quality"),
        ("quality:\n  min_workflow_steps: notint\n", "must be an integer"),
        ("quality:\n  min_anti_criteria: true\n", "must be an integer"),
    ],
)
def test_malformed_rejected(tmp_path, text, match):
    _write(tmp_path, text)
    with pytest.raises(ValueError, match=match):
        load_config(tmp_path)


def _seed_one(root: Path, status: str = "stub") -> None:
    (root / "registry").mkdir(parents=True, exist_ok=True)
    (root / "registry" / "skills.yaml").write_text(
        "skills:\n"
        f"  - {{id: sat.demo, name: Demo, group: sat, status: {status}, summary: s}}\n",
        encoding="utf-8",
    )
    (root / "registry" / "groups.yaml").write_text(
        "groups:\n  - {id: sat, title: SAT}\n", encoding="utf-8"
    )


def test_configured_extra_harness_flows_through(tmp_path):
    """A 4th harness in cogsecskills.yaml is generated by scaffold and accepted by validate."""
    from cogsecskills.scaffold import scaffold_skill
    from cogsecskills.validate import validate_library

    _seed_one(tmp_path)
    _write(tmp_path, "harnesses: [claude, codex, hermes, gemini]\n")
    cfg = load_config(tmp_path)
    scaffold_skill("sat.demo", root=tmp_path, harnesses=cfg.harnesses)
    assert (tmp_path / "skills" / "sat" / "demo" / "harness" / "gemini.md").is_file()
    result = validate_library(tmp_path, harnesses=cfg.harnesses)
    assert result.ok, [i.message for i in result.errors]


def test_configured_harness_gates_when_missing(tmp_path):
    """Requiring a harness whose adapter is absent is a validation error."""
    from cogsecskills.scaffold import scaffold_skill
    from cogsecskills.validate import validate_library

    _seed_one(tmp_path)
    scaffold_skill("sat.demo", root=tmp_path)  # default 3 harnesses, no gemini
    result = validate_library(
        tmp_path, harnesses=("claude", "codex", "hermes", "gemini")
    )
    assert any("gemini" in i.message for i in result.errors)
