"""Filesystem anchors and generated-asset path constants.

These are the lowest-level shared values for the manuscript-asset package.
This submodule imports nothing from its siblings.
"""

from __future__ import annotations

from pathlib import Path

from cogsecskills.core.locate import project_root

GENERATED_HEADER = (
    "<!-- Generated by `python -m cogsecskills manuscript-assets --write`; "
    "do not edit by hand. -->"
)

CATALOGUE_PATH = Path("manuscript/S10_skill_catalogue.md")
MATRIX_PATH = Path("manuscript/S11_skill_metadata_matrix.md")
DATA_JSON_PATH = Path("output/data/skill_catalogue.json")
DATA_CSV_PATH = Path("output/data/skill_catalogue.csv")

COVER_IMAGE_NAME = "cogsecskills_cover_installation.png"
COVER_IMAGE_MIRROR_PATH = Path("figures") / COVER_IMAGE_NAME


def _project_root(root: Path | None = None) -> Path:
    return Path(root) if root is not None else project_root()
